const ProductConstants = {
  FETCH_PRODUCT_REQUEST: "FETCH_PRODUCT_REQUEST",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILURE: "FETCH_PRODUCT_FAILURE",

  UPDATE_PRODUCT: "UPDATE_PRODUCT",
};
export default ProductConstants;
